Update blocklist.yml

diff --git a/.github/workflows/blocklist.yml b/.github/workflows/blocklist.yml
--- a/.github/workflows/blocklist.yml
+++ b/.github/workflows/blocklist.yml
@@ -24,6 +24,12 @@ jobs:
             -H "Accept: text/plain" \
             -o blacklist.txt
 
+          # Check that file contains at least one IPv4
+          if ! grep -qE '([0-9]{1,3}\.){3}[0-9]{1,3}' blacklist.txt; then
+            echo "Error: No IPs fetched. Possibly reached API usage limit."
+            exit 1
+          fi
+    
       - name: Generate release tag
         id: tag
         env:
